#!/bin/sh

case "$1" in
    start)
       echo "Loading ads1115 kernel module"
       cd /usr/bin/
       modprobe i2c-bcm2835
       modprobe i2c-dev
       ads1115_load
       ;;
    stop)
       echo "Unloading ads1115 kernel module"
       cd /usr/bin/
       ads1115_unload
       ;;
    *)
       echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0